/*
 * This source file was generated by the Gradle 'init' task
 */
package com.michaelvslalapan;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        System.out.println("Masukkan Menu yang Ingin Dipilih");
        System.out.printf("\nStart\nHelp\nPlants List\nZombiesList\nExit\n\n");

        Scanner input = new Scanner(System.in);

        boolean isProgramOver = false;
        
        while(isProgramOver == false){
            String menu = input.nextLine();

            switch(menu.toUpperCase()){
                case "START":
                    System.out.println("berhasil");
                    break;
                case "HELP":
                    break;
                case "PLANTS LIST":
                    break;
                case "ZOMBIESLIST":
                    break;
                case "EXIT":
                    isProgramOver = true;
                    break;
                default:
                    System.out.println("Masukkan Menu yang Benar");
                    break;
            }
            
        }
        
        input.close();
        

    }
}
